baseurl = "/"
title = "放送<span style='color:red'>禁</span>止 中文解析站"
copyright = "Copyright (c) 2019, all rights reserved."
languageCode = "en-US"
canonifyurls = true
paginate = 20
theme = "hugo-dusk"
enableRobotsTXT = true

googleAnalytics = ""
disqusShortname = ""

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "帖子"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "标签"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[taxonomies]
  category = "分类"
  group = "groups"
  series = "series"
  tag = "tags"

[author]
  name = "小风小水"

[params.meta]
  keywords = "放送禁止"
  description = "Personal blog."

[params]
  email = "myemail"
  github = "github id"
  #gitlab = "gitlab id"
  twitter = "twitter id"
  #linkedin = "linkedin id"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "white"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color
